spring:
  config:
    import: secrets.properties
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: ${DATABASE_URL_DEV}
    username: ${DATABASE_USER_DEV}
    password: ${DATABASE_PASSWORD_DEV}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    #hostname: 192.168.0.146
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      #defaultZone: http://41.78.80.108:8761/eureka/
       defaultZone : http://localhost:8761/eureka/

cloud:
  api:
    name: ${CLOUD_API_NAME}
    secret: ${CLOUD_API_SECRET}
    key: ${CLOUD_API_KEY}

mailgun:
  api:
    key: ${MAILGUN_API_KEY}
  domain: ${MAILGUN_DOMAIN}
  from:
    name: ${MAILGUN_FROM_NAME:Agro Smart Benue}
    email: ${MAILGUN_FROM_EMAIL}

server:
  port: 8080
  address: 0.0.0.0

rsa:
  public-key: classpath:keys/publicKey.pem
  private-key: classpath:keys/privateKey.pem